#!/bin/bash

#PBS -l select=1:ncpus=16:mem=60gb
#PBS -l walltime=12:00:00
#PBS -M abi.prakash@unsw.edu.au
#PBS -m ae

module add julia/1.8.2-ilp64
julia -e 'using Pkg;Pkg.activate("NEMStorageUnderUncertainty");Pkg.instantiate()'
julia --project="NEMStorageUnderUncertainty" -- NEMStorageUnderUncertainty/simulations/arbitrage_throughputpenalty_no_degradation/simulate_actual.jl $power $energy $cost
echo "Submitted ArbThroughputPenalty Actual $power MW $energy MWh $cost AUD/MWH"
